### PR TITLE
Allow custom tag parsers

### PR DESCRIPTION
**Pull request by djalexd**
It's not uncommon for banks to use their own variants of different tags. This MR allows devs to implement, if needed, their own tag parsers. In our particular case, statement number (tag28) has a totally weird format. 

By default nothing is changed, the parser works with tags out of the box, however can be customized by specifying `tags=dict(...)`.

### CODE REVIEW

**Comment by djalexd** [comment]
@WoLpH I wasn't able to `virtualenv + py.test` locally no matter how I tried. I mostly get this error:
`py.test: error: unrecognized arguments: --cov --cov-report term-missing --cov-report html --no-cov-on-fail --pep8 --flakes`. Any clues here? Thanks!

**Comment by djalexd** [comment]
hey @WoLpH thanks for your suggestions. I still couldn't make it work with `py.test`, but `tox` worked.  Now all tests are passing.

**Comment by djalexd** [comment]
So perhaps I should give you a bit of context. The purpose of this MR is to allow developers override the tag parsing behavior, with their own. Banks don't always adhere to MT940/other standards (which is our particular case, out of 6 banks, 1 doesn't do this). Ideally, we should take the matter back to the bank, but you're probably aware how slow those changes are going to happen (if at all).

It also defaults to the already existing tag regexes, so simply using the `mt940.models.Transactions` without `tags=...` will also work. Let me know what you think, thanks!

**Comment by WoLpH** [comment]
Given how inconsistent the banks are with implementing the standards you're absolutely right that there is a need for custom support per bank.

Your fix looks really nice and I've merged it with a few small changes. The test file could easily made passable by changing the way tag 28 is parsed. The only thing that appears to be missing is the `/` so instead of `01234/56789` they appear to use `01234589`.

Thanks for the awesome addition! I'll create a new release as soon as travis is done testing

**Comment by djalexd** [comment]
The only thing I think is missing is describing this behavior in README. I'll create another PR today for this :)

**Pull request merged**
