### PR TITLE
Update tox and travis configs.

### PR DESCRIPTION
**Pull request by benkonrath**
* Test on Python 2.5.
* Run tests from travis exclusively with tox.
* Set the Python version correctly for travis.
* Conistently indent travis.yml.

### CODE REVIEW

**Comment by benkonrath** [comment]
I still have to fix something because travis is running all the tests in one of the runs which shouldn't happen.

**Comment by benkonrath** [comment]
This is now ready. I think this is a much improved travis config.

**Comment by WoLpH** [comment]
Wow, indeed much better. Thank you! 

Since I'm currently moving I don't have my systems up and running yet but I'll push out a new release soon.

**Comment by WoLpH** [comment]
Apparently Github won't allow me to merge yet: Pull requests that have a failing status can’t be merged from a phone

**Comment by benkonrath** [comment]
There's no rush on getting this merged. Whenever you have time is good. Good luck with your move.

**Comment by WoLpH** [comment]
Thanks for all the help!

**Pull request merged**
