### PR TITLE
Feature/optimizations

### PR DESCRIPTION
**Pull request by ciupicri**
A couple of optimizations.

### CODE REVIEW

**Comment by WoLpH** [comment]
I'm not sure I see the point of the optimisation to be honest. Beyond your personal style changes the code seems identical?

**Comment by ciupicri** [comment]
A little bit of speed didn't hurt anyone and since the optimizations didn't require any radical changes, I implemented them.  As you've mentioned, the code is practically the same, just a bit faster (~2% for my files and hardware & software setup).

**Comment by WoLpH** [comment]
I'm honestly not a big fan of the `from ... import ...` style because it doesn't show where an import came from. In this case that is admittedly less of a problem, but it would be inconsistent with the rest of the source.

With regards to performance however, are you processing large enough files for that to be relevant? I have hardly looked at performance with this library because there hasn't been much need for it, but I'm sure I can greatly improve the performance with little effort if it is problematic that is.

**Comment by ciupicri** [comment]
[imaplib](https://github.com/python/cpython/blob/3.9/Lib/imaplib.py) from the standard library has both `import ...` and `from ... import`, but I can't disagree with your preferences.

Parsing takes less than a minute for me, so it's bearable, but of course I wouldn't mind if it would take less.

**Comment by WoLpH** [comment]
> [imaplib](https://github.com/python/cpython/blob/3.9/Lib/imaplib.py) from the standard library has both `import ...` and `from ... import`, but I can't disagree with your preferences.

Unfortunately the standard library isn't always the best example of pretty/Pythonic code. Take a look at the `logging` module for example, the naming and structure of that is very unlike Python.

I try to follow PEP 20 in that regard: https://www.python.org/dev/peps/pep-0020/
In this case specificially: "Explicit is better than implicit."

**Pull request closed without merging**
