### PR TITLE
Add support for getting final opening / closing balance on each transaction

### PR DESCRIPTION
**Pull request by benkonrath**
See #18 for explanation.

### CODE REVIEW

**Comment by WoLpH** [comment]
For some reason the tests appear to be failing but I'm pretty sure that's not related to your changes. I'm a bit busy at the moment but I'll have a look within a few weeks :)

**Comment by WoLpH** [comment]
Hmm, after running another test it does seem to be related to your changes but I'm not entirely sure how yet.

**Comment by benkonrath** [comment]
I actually think it is my code. When ever you have time to look into this, that's great.

This change seems to be working for me with an export from Knab and the monkey patch in #18 applied.

**Comment by benkonrath** [comment]
The issue with the current implementation (and the monkey patch) is that the opening balance isn't captured correctly because a new transaction is created with record 61 which comes after record 60F (opening balance).

I'm open to other solutions for this when you have time to look at it. Thanks.

**Comment by benkonrath** [comment]
I'm going to use this branch in my project and will update it if I have further changes. I'll try to update the tests as well.

**Comment by benkonrath** [comment]
I forgot to mention that an MT940 block with multiple 61 records will only have the final opening balance on the first transaction, and the final closing balance on the last transaction of the block. This is something that I can document if you want to merge this PR.

We could also generate these values if you think that's better for consistency.

**Comment by benkonrath** [comment]
Just a quick note to let you know that I'm still working on this so you shouldn't merge it. My other PRs come out of this work.

**Comment by benkonrath** [comment]
This is ready for review. There will be some merge conflicts with my other PRs so just let me know if you want me to rebase.

Some notes about the implementation:

* I didn't make the transaction based final opening / closing balance the default behavior but instead provided directions on how to set it up.
* The final opening and closing balance is not available on every transaction as it's not available in the STA file for each :61: tag.
* You need to manually set the currency when using the final opening / closing balance on each transaction. This is related to how the currency is set on the Amount objects. The could be fixed but I'm not sure what the best approach would be.

**Comment by WoLpH** [comment]
Thanks for the patch, I've merged it all and I'm running the tests now. As soon as all tests succeed I'll push out a new release :)

**Pull request closed without merging**
