### PR TITLE
Feature/datetime

### PR DESCRIPTION
**Pull request by ciupicri**
As a side note, `Date` and `DateTime` should probably be renamed to `parse_date` and `parse_datetime`.

### CODE REVIEW

**Comment by WoLpH** [comment]
Thank you for the pull request, but I'm not entirely sure what you're trying to fix yet. Can you clarify?

Additionally this pull request breaks backwards compatibility because the returned objects don't inherit `Model` anymore which all other objects do.

**Comment by ciupicri** [comment]
https://foss.heptapod.net/openpyxl/openpyxl/-/issues/1538

I didn't know that it's mandatory to inherit from `Model`. The documentation doesn't say anything about this.

**Comment by WoLpH** [comment]
You're right, it isn't mentioned. But changing it changes the behaviour of the library and people might be doing an `isinstance(..., Model)` which would break so I'm a bit hesitant to merge changes like that.

For what it's worth, the justification in the linked issue seems wrong to me. With older versions of Python that was still valid but it currently seems slower. I'm getting 90ns vs 65ns:
```
Python 3.8.1 (default, Mar 13 2020, 12:47:42)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from datetime import datetime

In [2]: class DateTime(datetime):
   ...:     pass
   ...:

In [3]: a = datetime.now()

In [4]: b = DateTime.now()

In [5]: a
Out[5]: datetime.datetime(2020, 10, 4, 21, 44, 43, 416525)

In [6]: b
Out[6]: DateTime(2020, 10, 4, 21, 44, 57, 454406)

In [7]: %timeit isinstance(a, datetime)
64.6 ns ± 0.704 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [8]: %timeit isinstance(b, datetime)
64.4 ns ± 0.544 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [9]: %timeit type(a) is datetime
90.3 ns ± 1.05 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [10]: %timeit type(b) is datetime
86.7 ns ± 0.708 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [11]: type(a) is datetime
Out[11]: True

In [12]: type(b) is datetime
Out[12]: False
```

More constructively however, I wouldn't oppose a flag to return the native classes instances instead of the model subclasses.

**Comment by ciupicri** [comment]
For what it's worth, [openpyxl][1] 3.0 has added support for subclasses.

Anyway, could you elaborate a bit on the flag idea?


[1]: https://foss.heptapod.net/openpyxl/openpyxl/-/issues/1538#note_146362

**Comment by WoLpH** [comment]
What I mean is that we would have a `NativeDateTime` and a `DateTime` (the latter inherits the `Model` as well as the `NativeDateTIme`) and depending on the configuration of the parser return one of the two.

**Pull request closed without merging**
