### PR TITLE
Fix for #53 Sberbank Statement format

### PR DESCRIPTION
**Pull request by csfulop**
Statement regex is updated to allow spaces

### CODE REVIEW

**Comment by WoLpH** [comment]
Thanks for the help! I don't have time to fully review it but the pytest-runner issue is nothing to worry about. That bug has been reported upstream but the developer can't easily fix it: https://github.com/pytest-dev/pytest-runner/issues/36

I'm still pondering whether to simply drop the pytest-runner integration and replace it with a few lines of code: https://pytest.readthedocs.io/en/reorganize-docs/goodpractices.html#manual-integration
Or find a way to ignore the pep8 incompliance in pytest-runner

**Comment by csfulop** [comment]
For me it is strange that for some python versions it pass and for some it fails.
And it complains for .eggs dir, there are some cached dependencies there, I think it should not be checked.
Now in Christmas holiday I have some free time, I can have a look and try to ignore :)

**Comment by csfulop** [comment]
Now there is only problem with python 3.3.
It seems it conflicts with pytest:
```
pytest requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 3.3.6
```
Are you really need 3.3? If not then we can drop it.

**Comment by WoLpH** [comment]
No, we can drop 3.3 :)
That's the thing with packages like these, the tests work fine for several months and after that they break because something became deprecated ;)

**Comment by csfulop** [comment]
Ok, now 3.3 is dropped and travis is green again :)

**Comment by WoLpH** [comment]
Awesome! Thank you so much for the help. I'll push a new release soon

**Pull request merged**
